elasticsearch.hosts: https://es-node1:9200
#elasticsearch.url: https://es-node1:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: admin
elasticsearch.password: admin
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

server.host: 0.0.0.0

server.ssl.enabled: true
server.ssl.certificateAuthorities: /usr/share/elasticsearch/config/root-ca.pem
server.ssl.certificate: /usr/share/elasticsearch/config/node.pem
server.ssl.key: /usr/share/elasticsearch/config/node-key.pem
